# Generated by Django 2.0.2 on 2018-02-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['committee', 'due_date', 'status']},
        ),
    ]
