# Generated by Django 2.0.2 on 2018-03-10 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_auto_20180303_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='head',
        ),
        migrations.AddField(
            model_name='committee',
            name='heads',
            field=models.ManyToManyField(null=True, related_name='heads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned',
            field=models.ForeignKey(null=True, on_delete='SET_NULL', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='committee',
            name='members',
            field=models.ManyToManyField(null=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
