# Generated by Django 2.0.2 on 2018-03-10 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20180310_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='heads',
            field=models.ManyToManyField(blank=True, related_name='heads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='committee',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
